apiVersion: v1
kind: Service
metadata:
  name: glfs
  labels:
    app: glfs
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: glfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glfs
  labels:
    app: glfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glfs
  template:
    metadata:
      labels:
        app: glfs
    spec:
      containers:
        - name: glfs
          image: glfs:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
